<?php
/**
 * ResponseOfPersonalCertificate
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 内测云分发开发者API接口
 *
 * 内测云开发者服务平台应用程序接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henryxm@163.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ResponseOfPersonalCertificate Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class ResponseOfPersonalCertificate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResponseOfPersonalCertificate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'action' => 'string',
        'algorithm' => 'string',
        'ciphertext' => 'string',
        'code' => 'int',
        'data' => '\OpenAPI\Client\Model\PersonalCertificate',
        'error' => 'string',
        'msg' => 'string',
        'result' => '\OpenAPI\Client\Model\Result',
        'session' => 'string',
        'success' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'action' => null,
        'algorithm' => null,
        'ciphertext' => null,
        'code' => 'int32',
        'data' => null,
        'error' => null,
        'msg' => null,
        'result' => null,
        'session' => null,
        'success' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action' => 'action',
        'algorithm' => 'algorithm',
        'ciphertext' => 'ciphertext',
        'code' => 'code',
        'data' => 'data',
        'error' => 'error',
        'msg' => 'msg',
        'result' => 'result',
        'session' => 'session',
        'success' => 'success'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action' => 'setAction',
        'algorithm' => 'setAlgorithm',
        'ciphertext' => 'setCiphertext',
        'code' => 'setCode',
        'data' => 'setData',
        'error' => 'setError',
        'msg' => 'setMsg',
        'result' => 'setResult',
        'session' => 'setSession',
        'success' => 'setSuccess'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action' => 'getAction',
        'algorithm' => 'getAlgorithm',
        'ciphertext' => 'getCiphertext',
        'code' => 'getCode',
        'data' => 'getData',
        'error' => 'getError',
        'msg' => 'getMsg',
        'result' => 'getResult',
        'session' => 'getSession',
        'success' => 'getSuccess'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const ACTION_GET_AES_KEY = 'GET_AES_KEY';
    const ACTION_NONE = 'NONE';
    const ACTION_REFRESH_SERVER_PUBLIC_KEY = 'REFRESH_SERVER_PUBLIC_KEY';
    const ACTION_RETRY_LATER = 'RETRY_LATER';
    const ACTION_RE_LOGIN = 'RE_LOGIN';
    const ACTION_UPDATE_CLIENT_VERSION = 'UPDATE_CLIENT_VERSION';
    const ACTION_UPLOAD_CLIENT_PUBLIC_KEY = 'UPLOAD_CLIENT_PUBLIC_KEY';
    const ERROR_ACCEPTED = 'ACCEPTED';
    const ERROR_ACCESS_RATE_LIMIT = 'ACCESS_RATE_LIMIT';
    const ERROR_ACCOUNT_CANCELLED = 'ACCOUNT_CANCELLED';
    const ERROR_ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
    const ERROR_ACCOUNT_LOCKED = 'ACCOUNT_LOCKED';
    const ERROR_ACCOUNT_NOT_ACTIVATED = 'ACCOUNT_NOT_ACTIVATED';
    const ERROR_AES_DECRYPTED_DATA_EMPTY = 'AES_DECRYPTED_DATA_EMPTY';
    const ERROR_AES_DECRYPT_FAILED = 'AES_DECRYPT_FAILED';
    const ERROR_AES_ENCRYPTED_DATA_EMPTY = 'AES_ENCRYPTED_DATA_EMPTY';
    const ERROR_AES_ENCRYPT_FAILED = 'AES_ENCRYPT_FAILED';
    const ERROR_AES_KEY_EXPIRED = 'AES_KEY_EXPIRED';
    const ERROR_AES_KEY_EXPIRING_SOON = 'AES_KEY_EXPIRING_SOON';
    const ERROR_AES_KEY_FORMAT_ERROR = 'AES_KEY_FORMAT_ERROR';
    const ERROR_AES_KEY_GENERATE_FAILED = 'AES_KEY_GENERATE_FAILED';
    const ERROR_AES_KEY_LENGTH_ERROR = 'AES_KEY_LENGTH_ERROR';
    const ERROR_AES_KEY_NOT_FOUND = 'AES_KEY_NOT_FOUND';
    const ERROR_AES_MODE_NOT_SUPPORTED = 'AES_MODE_NOT_SUPPORTED';
    const ERROR_AES_PADDING_NOT_SUPPORTED = 'AES_PADDING_NOT_SUPPORTED';
    const ERROR_AES_VECTOR_FORMAT_ERROR = 'AES_VECTOR_FORMAT_ERROR';
    const ERROR_AES_VECTOR_LENGTH_ERROR = 'AES_VECTOR_LENGTH_ERROR';
    const ERROR_ALREADY_REPORTED = 'ALREADY_REPORTED';
    const ERROR_BAD_GATEWAY = 'BAD_GATEWAY';
    const ERROR_BAD_REQUEST = 'BAD_REQUEST';
    const ERROR_BUSINESS_ERROR = 'BUSINESS_ERROR';
    const ERROR_CAPTCHA_ERROR = 'CAPTCHA_ERROR';
    const ERROR_CAPTCHA_EXPIRED = 'CAPTCHA_EXPIRED';
    const ERROR_CONFLICT = 'CONFLICT';
    const ERROR__CONTINUE = 'CONTINUE';
    const ERROR_CREATED = 'CREATED';
    const ERROR_DATABASE_BACKUP_FAILED = 'DATABASE_BACKUP_FAILED';
    const ERROR_DATABASE_CHECK_CONSTRAINT_VIOLATION = 'DATABASE_CHECK_CONSTRAINT_VIOLATION';
    const ERROR_DATABASE_COLUMN_NOT_FOUND = 'DATABASE_COLUMN_NOT_FOUND';
    const ERROR_DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED';
    const ERROR_DATABASE_CONNECTION_POOL_EXHAUSTED = 'DATABASE_CONNECTION_POOL_EXHAUSTED';
    const ERROR_DATABASE_DEADLOCK = 'DATABASE_DEADLOCK';
    const ERROR_DATABASE_DELETE_FAILED = 'DATABASE_DELETE_FAILED';
    const ERROR_DATABASE_DUPLICATE_KEY = 'DATABASE_DUPLICATE_KEY';
    const ERROR_DATABASE_FOREIGN_KEY_VIOLATION = 'DATABASE_FOREIGN_KEY_VIOLATION';
    const ERROR_DATABASE_INDEX_NOT_FOUND = 'DATABASE_INDEX_NOT_FOUND';
    const ERROR_DATABASE_INSERT_FAILED = 'DATABASE_INSERT_FAILED';
    const ERROR_DATABASE_NOT_NULL_VIOLATION = 'DATABASE_NOT_NULL_VIOLATION';
    const ERROR_DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED';
    const ERROR_DATABASE_PERMISSION_DENIED = 'DATABASE_PERMISSION_DENIED';
    const ERROR_DATABASE_QUERY_FAILED = 'DATABASE_QUERY_FAILED';
    const ERROR_DATABASE_READ_ONLY = 'DATABASE_READ_ONLY';
    const ERROR_DATABASE_RESTORE_FAILED = 'DATABASE_RESTORE_FAILED';
    const ERROR_DATABASE_SQL_SYNTAX_ERROR = 'DATABASE_SQL_SYNTAX_ERROR';
    const ERROR_DATABASE_TABLE_NOT_FOUND = 'DATABASE_TABLE_NOT_FOUND';
    const ERROR_DATABASE_TIMEOUT = 'DATABASE_TIMEOUT';
    const ERROR_DATABASE_TRANSACTION_FAILED = 'DATABASE_TRANSACTION_FAILED';
    const ERROR_DATABASE_UNIQUE_CONSTRAINT_VIOLATION = 'DATABASE_UNIQUE_CONSTRAINT_VIOLATION';
    const ERROR_DATABASE_UPDATE_FAILED = 'DATABASE_UPDATE_FAILED';
    const ERROR_DATABASE_VERSION_INCOMPATIBLE = 'DATABASE_VERSION_INCOMPATIBLE';
    const ERROR_DATA_ALREADY_EXISTS = 'DATA_ALREADY_EXISTS';
    const ERROR_DATA_CONSTRAINT_VIOLATION = 'DATA_CONSTRAINT_VIOLATION';
    const ERROR_DATA_FORMAT_ERROR = 'DATA_FORMAT_ERROR';
    const ERROR_DATA_INTEGRITY_ERROR = 'DATA_INTEGRITY_ERROR';
    const ERROR_DATA_NOT_FOUND = 'DATA_NOT_FOUND';
    const ERROR_DATA_RANGE_ERROR = 'DATA_RANGE_ERROR';
    const ERROR_DATA_RELATION_ERROR = 'DATA_RELATION_ERROR';
    const ERROR_DATA_STATUS_ERROR = 'DATA_STATUS_ERROR';
    const ERROR_DATA_VERSION_CONFLICT = 'DATA_VERSION_CONFLICT';
    const ERROR_EARLY_HINTS = 'EARLY_HINTS';
    const ERROR_EXPECTATION_FAILED = 'EXPECTATION_FAILED';
    const ERROR_FAILED_DEPENDENCY = 'FAILED_DEPENDENCY';
    const ERROR_FEATURE_NOT_AVAILABLE = 'FEATURE_NOT_AVAILABLE';
    const ERROR_FORBIDDEN = 'FORBIDDEN';
    const ERROR_FORCE_ENCRYPT_REQUEST_REQUIRED = 'FORCE_ENCRYPT_REQUEST_REQUIRED';
    const ERROR_FORCE_ENCRYPT_SESSION_REQUIRED = 'FORCE_ENCRYPT_SESSION_REQUIRED';
    const ERROR_FOUND = 'FOUND';
    const ERROR_GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT';
    const ERROR_GONE = 'GONE';
    const ERROR_HTTP_VERSION_NOT_SUPPORTED = 'HTTP_VERSION_NOT_SUPPORTED';
    const ERROR_IM_USED = 'IM_USED';
    const ERROR_INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE';
    const ERROR_INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    const ERROR_IP_FORBIDDEN = 'IP_FORBIDDEN';
    const ERROR_LENGTH_REQUIRED = 'LENGTH_REQUIRED';
    const ERROR_LOCKED = 'LOCKED';
    const ERROR_LOGIN_EXPIRED = 'LOGIN_EXPIRED';
    const ERROR_LOGIN_FAILED = 'LOGIN_FAILED';
    const ERROR_LOOP_DETECTED = 'LOOP_DETECTED';
    const ERROR_METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    const ERROR_MOVED_PERMANENTLY = 'MOVED_PERMANENTLY';
    const ERROR_MULTIPLE_CHOICES = 'MULTIPLE_CHOICES';
    const ERROR_MULTI_STATUS = 'MULTI_STATUS';
    const ERROR_NETWORK_AUTHENTICATION_REQUIRED = 'NETWORK_AUTHENTICATION_REQUIRED';
    const ERROR_NON_AUTHORITATIVE_INFORMATION = 'NON_AUTHORITATIVE_INFORMATION';
    const ERROR_NOT_ACCEPTABLE = 'NOT_ACCEPTABLE';
    const ERROR_NOT_EXTENDED = 'NOT_EXTENDED';
    const ERROR_NOT_FOUND = 'NOT_FOUND';
    const ERROR_NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
    const ERROR_NOT_MODIFIED = 'NOT_MODIFIED';
    const ERROR_NO_CONTENT = 'NO_CONTENT';
    const ERROR_OK = 'OK';
    const ERROR_OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED';
    const ERROR_OPERATION_TIMEOUT = 'OPERATION_TIMEOUT';
    const ERROR_PARTIAL_CONTENT = 'PARTIAL_CONTENT';
    const ERROR_PASSWORD_EXPIRED = 'PASSWORD_EXPIRED';
    const ERROR_PASSWORD_WEAK = 'PASSWORD_WEAK';
    const ERROR_PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE';
    const ERROR_PAYMENT_REQUIRED = 'PAYMENT_REQUIRED';
    const ERROR_PERMANENT_REDIRECT = 'PERMANENT_REDIRECT';
    const ERROR_PERMISSION_DENIED = 'PERMISSION_DENIED';
    const ERROR_PRECONDITION_FAILED = 'PRECONDITION_FAILED';
    const ERROR_PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED';
    const ERROR_PROCESSING = 'PROCESSING';
    const ERROR_PROXY_AUTHENTICATION_REQUIRED = 'PROXY_AUTHENTICATION_REQUIRED';
    const ERROR_RANGE_NOT_SATISFIABLE = 'RANGE_NOT_SATISFIABLE';
    const ERROR_REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';
    const ERROR_REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID';
    const ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE = 'REQUEST_HEADER_FIELDS_TOO_LARGE';
    const ERROR_REQUEST_TIMEOUT = 'REQUEST_TIMEOUT';
    const ERROR_RESET_CONTENT = 'RESET_CONTENT';
    const ERROR_RESOURCE_LOCKED = 'RESOURCE_LOCKED';
    const ERROR_RSA_CLIENT_PUBLIC_KEY_EXPIRING_SOON = 'RSA_CLIENT_PUBLIC_KEY_EXPIRING_SOON';
    const ERROR_RSA_CLIENT_PUBLIC_KEY_NOT_FOUND = 'RSA_CLIENT_PUBLIC_KEY_NOT_FOUND';
    const ERROR_RSA_DECRYPT_FAILED = 'RSA_DECRYPT_FAILED';
    const ERROR_RSA_ENCRYPT_FAILED = 'RSA_ENCRYPT_FAILED';
    const ERROR_RSA_KEY_FORMAT_ERROR = 'RSA_KEY_FORMAT_ERROR';
    const ERROR_RSA_KEY_GENERATE_FAILED = 'RSA_KEY_GENERATE_FAILED';
    const ERROR_RSA_KEY_LENGTH_ERROR = 'RSA_KEY_LENGTH_ERROR';
    const ERROR_RSA_KEY_PAIR_EXPIRING_SOON = 'RSA_KEY_PAIR_EXPIRING_SOON';
    const ERROR_RSA_KEY_PAIR_MISMATCH = 'RSA_KEY_PAIR_MISMATCH';
    const ERROR_RSA_KEY_PAIR_NOT_FOUND = 'RSA_KEY_PAIR_NOT_FOUND';
    const ERROR_RSA_PRIVATE_KEY_NOT_FOUND = 'RSA_PRIVATE_KEY_NOT_FOUND';
    const ERROR_RSA_PRIVATE_KEY_PARSE_ERROR = 'RSA_PRIVATE_KEY_PARSE_ERROR';
    const ERROR_RSA_PUBLIC_KEY_PARSE_ERROR = 'RSA_PUBLIC_KEY_PARSE_ERROR';
    const ERROR_RSA_SESSION_INVALID = 'RSA_SESSION_INVALID';
    const ERROR_RSA_SESSION_REQUIRED = 'RSA_SESSION_REQUIRED';
    const ERROR_SEE_OTHER = 'SEE_OTHER';
    const ERROR_SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    const ERROR_SESSION_EXPIRED = 'SESSION_EXPIRED';
    const ERROR_SESSION_INVALID = 'SESSION_INVALID';
    const ERROR_SUCCESS = 'SUCCESS';
    const ERROR_SWITCHING_PROTOCOLS = 'SWITCHING_PROTOCOLS';
    const ERROR_SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE';
    const ERROR_TEMPORARY_REDIRECT = 'TEMPORARY_REDIRECT';
    const ERROR_THIRD_PARTY_LOGIN_FAILED = 'THIRD_PARTY_LOGIN_FAILED';
    const ERROR_TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    const ERROR_TOKEN_INVALID = 'TOKEN_INVALID';
    const ERROR_TOO_EARLY = 'TOO_EARLY';
    const ERROR_TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    const ERROR_UNAUTHORIZED = 'UNAUTHORIZED';
    const ERROR_UNAVAILABLE_FOR_LEGAL_REASONS = 'UNAVAILABLE_FOR_LEGAL_REASONS';
    const ERROR_UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    const ERROR_UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY';
    const ERROR_UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE';
    const ERROR_UPGRADE_REQUIRED = 'UPGRADE_REQUIRED';
    const ERROR_URI_TOO_LONG = 'URI_TOO_LONG';
    const ERROR_USER_NOT_LOGIN = 'USER_NOT_LOGIN';
    const ERROR_USE_PROXY = 'USE_PROXY';
    const ERROR_VARIANT_ALSO_NEGOTIATES = 'VARIANT_ALSO_NEGOTIATES';
    const ERROR_VERSION_INCOMPATIBLE = 'VERSION_INCOMPATIBLE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues()
    {
        return [
            self::ACTION_GET_AES_KEY,
            self::ACTION_NONE,
            self::ACTION_REFRESH_SERVER_PUBLIC_KEY,
            self::ACTION_RETRY_LATER,
            self::ACTION_RE_LOGIN,
            self::ACTION_UPDATE_CLIENT_VERSION,
            self::ACTION_UPLOAD_CLIENT_PUBLIC_KEY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getErrorAllowableValues()
    {
        return [
            self::ERROR_ACCEPTED,
            self::ERROR_ACCESS_RATE_LIMIT,
            self::ERROR_ACCOUNT_CANCELLED,
            self::ERROR_ACCOUNT_DISABLED,
            self::ERROR_ACCOUNT_LOCKED,
            self::ERROR_ACCOUNT_NOT_ACTIVATED,
            self::ERROR_AES_DECRYPTED_DATA_EMPTY,
            self::ERROR_AES_DECRYPT_FAILED,
            self::ERROR_AES_ENCRYPTED_DATA_EMPTY,
            self::ERROR_AES_ENCRYPT_FAILED,
            self::ERROR_AES_KEY_EXPIRED,
            self::ERROR_AES_KEY_EXPIRING_SOON,
            self::ERROR_AES_KEY_FORMAT_ERROR,
            self::ERROR_AES_KEY_GENERATE_FAILED,
            self::ERROR_AES_KEY_LENGTH_ERROR,
            self::ERROR_AES_KEY_NOT_FOUND,
            self::ERROR_AES_MODE_NOT_SUPPORTED,
            self::ERROR_AES_PADDING_NOT_SUPPORTED,
            self::ERROR_AES_VECTOR_FORMAT_ERROR,
            self::ERROR_AES_VECTOR_LENGTH_ERROR,
            self::ERROR_ALREADY_REPORTED,
            self::ERROR_BAD_GATEWAY,
            self::ERROR_BAD_REQUEST,
            self::ERROR_BUSINESS_ERROR,
            self::ERROR_CAPTCHA_ERROR,
            self::ERROR_CAPTCHA_EXPIRED,
            self::ERROR_CONFLICT,
            self::ERROR__CONTINUE,
            self::ERROR_CREATED,
            self::ERROR_DATABASE_BACKUP_FAILED,
            self::ERROR_DATABASE_CHECK_CONSTRAINT_VIOLATION,
            self::ERROR_DATABASE_COLUMN_NOT_FOUND,
            self::ERROR_DATABASE_CONNECTION_FAILED,
            self::ERROR_DATABASE_CONNECTION_POOL_EXHAUSTED,
            self::ERROR_DATABASE_DEADLOCK,
            self::ERROR_DATABASE_DELETE_FAILED,
            self::ERROR_DATABASE_DUPLICATE_KEY,
            self::ERROR_DATABASE_FOREIGN_KEY_VIOLATION,
            self::ERROR_DATABASE_INDEX_NOT_FOUND,
            self::ERROR_DATABASE_INSERT_FAILED,
            self::ERROR_DATABASE_NOT_NULL_VIOLATION,
            self::ERROR_DATABASE_OPERATION_FAILED,
            self::ERROR_DATABASE_PERMISSION_DENIED,
            self::ERROR_DATABASE_QUERY_FAILED,
            self::ERROR_DATABASE_READ_ONLY,
            self::ERROR_DATABASE_RESTORE_FAILED,
            self::ERROR_DATABASE_SQL_SYNTAX_ERROR,
            self::ERROR_DATABASE_TABLE_NOT_FOUND,
            self::ERROR_DATABASE_TIMEOUT,
            self::ERROR_DATABASE_TRANSACTION_FAILED,
            self::ERROR_DATABASE_UNIQUE_CONSTRAINT_VIOLATION,
            self::ERROR_DATABASE_UPDATE_FAILED,
            self::ERROR_DATABASE_VERSION_INCOMPATIBLE,
            self::ERROR_DATA_ALREADY_EXISTS,
            self::ERROR_DATA_CONSTRAINT_VIOLATION,
            self::ERROR_DATA_FORMAT_ERROR,
            self::ERROR_DATA_INTEGRITY_ERROR,
            self::ERROR_DATA_NOT_FOUND,
            self::ERROR_DATA_RANGE_ERROR,
            self::ERROR_DATA_RELATION_ERROR,
            self::ERROR_DATA_STATUS_ERROR,
            self::ERROR_DATA_VERSION_CONFLICT,
            self::ERROR_EARLY_HINTS,
            self::ERROR_EXPECTATION_FAILED,
            self::ERROR_FAILED_DEPENDENCY,
            self::ERROR_FEATURE_NOT_AVAILABLE,
            self::ERROR_FORBIDDEN,
            self::ERROR_FORCE_ENCRYPT_REQUEST_REQUIRED,
            self::ERROR_FORCE_ENCRYPT_SESSION_REQUIRED,
            self::ERROR_FOUND,
            self::ERROR_GATEWAY_TIMEOUT,
            self::ERROR_GONE,
            self::ERROR_HTTP_VERSION_NOT_SUPPORTED,
            self::ERROR_IM_USED,
            self::ERROR_INSUFFICIENT_STORAGE,
            self::ERROR_INTERNAL_SERVER_ERROR,
            self::ERROR_IP_FORBIDDEN,
            self::ERROR_LENGTH_REQUIRED,
            self::ERROR_LOCKED,
            self::ERROR_LOGIN_EXPIRED,
            self::ERROR_LOGIN_FAILED,
            self::ERROR_LOOP_DETECTED,
            self::ERROR_METHOD_NOT_ALLOWED,
            self::ERROR_MOVED_PERMANENTLY,
            self::ERROR_MULTIPLE_CHOICES,
            self::ERROR_MULTI_STATUS,
            self::ERROR_NETWORK_AUTHENTICATION_REQUIRED,
            self::ERROR_NON_AUTHORITATIVE_INFORMATION,
            self::ERROR_NOT_ACCEPTABLE,
            self::ERROR_NOT_EXTENDED,
            self::ERROR_NOT_FOUND,
            self::ERROR_NOT_IMPLEMENTED,
            self::ERROR_NOT_MODIFIED,
            self::ERROR_NO_CONTENT,
            self::ERROR_OK,
            self::ERROR_OPERATION_NOT_ALLOWED,
            self::ERROR_OPERATION_TIMEOUT,
            self::ERROR_PARTIAL_CONTENT,
            self::ERROR_PASSWORD_EXPIRED,
            self::ERROR_PASSWORD_WEAK,
            self::ERROR_PAYLOAD_TOO_LARGE,
            self::ERROR_PAYMENT_REQUIRED,
            self::ERROR_PERMANENT_REDIRECT,
            self::ERROR_PERMISSION_DENIED,
            self::ERROR_PRECONDITION_FAILED,
            self::ERROR_PRECONDITION_REQUIRED,
            self::ERROR_PROCESSING,
            self::ERROR_PROXY_AUTHENTICATION_REQUIRED,
            self::ERROR_RANGE_NOT_SATISFIABLE,
            self::ERROR_REFRESH_TOKEN_EXPIRED,
            self::ERROR_REFRESH_TOKEN_INVALID,
            self::ERROR_REQUEST_HEADER_FIELDS_TOO_LARGE,
            self::ERROR_REQUEST_TIMEOUT,
            self::ERROR_RESET_CONTENT,
            self::ERROR_RESOURCE_LOCKED,
            self::ERROR_RSA_CLIENT_PUBLIC_KEY_EXPIRING_SOON,
            self::ERROR_RSA_CLIENT_PUBLIC_KEY_NOT_FOUND,
            self::ERROR_RSA_DECRYPT_FAILED,
            self::ERROR_RSA_ENCRYPT_FAILED,
            self::ERROR_RSA_KEY_FORMAT_ERROR,
            self::ERROR_RSA_KEY_GENERATE_FAILED,
            self::ERROR_RSA_KEY_LENGTH_ERROR,
            self::ERROR_RSA_KEY_PAIR_EXPIRING_SOON,
            self::ERROR_RSA_KEY_PAIR_MISMATCH,
            self::ERROR_RSA_KEY_PAIR_NOT_FOUND,
            self::ERROR_RSA_PRIVATE_KEY_NOT_FOUND,
            self::ERROR_RSA_PRIVATE_KEY_PARSE_ERROR,
            self::ERROR_RSA_PUBLIC_KEY_PARSE_ERROR,
            self::ERROR_RSA_SESSION_INVALID,
            self::ERROR_RSA_SESSION_REQUIRED,
            self::ERROR_SEE_OTHER,
            self::ERROR_SERVICE_UNAVAILABLE,
            self::ERROR_SESSION_EXPIRED,
            self::ERROR_SESSION_INVALID,
            self::ERROR_SUCCESS,
            self::ERROR_SWITCHING_PROTOCOLS,
            self::ERROR_SYSTEM_MAINTENANCE,
            self::ERROR_TEMPORARY_REDIRECT,
            self::ERROR_THIRD_PARTY_LOGIN_FAILED,
            self::ERROR_TOKEN_EXPIRED,
            self::ERROR_TOKEN_INVALID,
            self::ERROR_TOO_EARLY,
            self::ERROR_TOO_MANY_REQUESTS,
            self::ERROR_UNAUTHORIZED,
            self::ERROR_UNAVAILABLE_FOR_LEGAL_REASONS,
            self::ERROR_UNKNOWN_ERROR,
            self::ERROR_UNPROCESSABLE_ENTITY,
            self::ERROR_UNSUPPORTED_MEDIA_TYPE,
            self::ERROR_UPGRADE_REQUIRED,
            self::ERROR_URI_TOO_LONG,
            self::ERROR_USER_NOT_LOGIN,
            self::ERROR_USE_PROXY,
            self::ERROR_VARIANT_ALSO_NEGOTIATES,
            self::ERROR_VERSION_INCOMPATIBLE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['action'] = $data['action'] ?? null;
        $this->container['algorithm'] = $data['algorithm'] ?? null;
        $this->container['ciphertext'] = $data['ciphertext'] ?? null;
        $this->container['code'] = $data['code'] ?? null;
        $this->container['data'] = $data['data'] ?? null;
        $this->container['error'] = $data['error'] ?? null;
        $this->container['msg'] = $data['msg'] ?? null;
        $this->container['result'] = $data['result'] ?? null;
        $this->container['session'] = $data['session'] ?? null;
        $this->container['success'] = $data['success'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['action']) && !in_array($this->container['action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'action', must be one of '%s'",
                $this->container['action'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        $allowedValues = $this->getErrorAllowableValues();
        if (!is_null($this->container['error']) && !in_array($this->container['error'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'error', must be one of '%s'",
                $this->container['error'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string|null $action action
     *
     * @return self
     */
    public function setAction($action)
    {
        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($action) && !in_array($action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'action', must be one of '%s'",
                    $action,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets algorithm
     *
     * @return string|null
     */
    public function getAlgorithm()
    {
        return $this->container['algorithm'];
    }

    /**
     * Sets algorithm
     *
     * @param string|null $algorithm algorithm
     *
     * @return self
     */
    public function setAlgorithm($algorithm)
    {
        $this->container['algorithm'] = $algorithm;

        return $this;
    }

    /**
     * Gets ciphertext
     *
     * @return string|null
     */
    public function getCiphertext()
    {
        return $this->container['ciphertext'];
    }

    /**
     * Sets ciphertext
     *
     * @param string|null $ciphertext ciphertext
     *
     * @return self
     */
    public function setCiphertext($ciphertext)
    {
        $this->container['ciphertext'] = $ciphertext;

        return $this;
    }

    /**
     * Gets code
     *
     * @return int
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param int $code 响应代码
     *
     * @return self
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \OpenAPI\Client\Model\PersonalCertificate|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \OpenAPI\Client\Model\PersonalCertificate|null $data data
     *
     * @return self
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        $allowedValues = $this->getErrorAllowableValues();
        if (!is_null($error) && !in_array($error, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'error', must be one of '%s'",
                    $error,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets msg
     *
     * @return string|null
     */
    public function getMsg()
    {
        return $this->container['msg'];
    }

    /**
     * Sets msg
     *
     * @param string|null $msg 错误信息:成功时为空或为success
     *
     * @return self
     */
    public function setMsg($msg)
    {
        $this->container['msg'] = $msg;

        return $this;
    }

    /**
     * Gets result
     *
     * @return \OpenAPI\Client\Model\Result|null
     */
    public function getResult()
    {
        return $this->container['result'];
    }

    /**
     * Sets result
     *
     * @param \OpenAPI\Client\Model\Result|null $result result
     *
     * @return self
     */
    public function setResult($result)
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets session
     *
     * @return string|null
     */
    public function getSession()
    {
        return $this->container['session'];
    }

    /**
     * Sets session
     *
     * @param string|null $session session
     *
     * @return self
     */
    public function setSession($session)
    {
        $this->container['session'] = $session;

        return $this;
    }

    /**
     * Gets success
     *
     * @return bool|null
     */
    public function getSuccess()
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param bool|null $success success
     *
     * @return self
     */
    public function setSuccess($success)
    {
        $this->container['success'] = $success;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


